spring.application.name=cron-scheduler
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5434/cronscheduler
spring.datasource.username=cronscheduler
spring.datasource.password=cronscheduler

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
